//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamerShopStore.BDSHKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID_employee { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> ID_post { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<bool> Visible { get; set; }
        public byte[] PhotoEmployee { get; set; }
    
        public virtual PostEmp PostEmp { get; set; }
    }
}
