//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamerShopStore.BDSHKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int ID_income { get; set; }
        public string Date { get; set; }
        public Nullable<decimal> Income1 { get; set; }
        public Nullable<int> ID_quarter { get; set; }
    
        public virtual Quarter Quarter { get; set; }
    }
}
