//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamerShopStore.BDSHKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int ID_tovar { get; set; }
        public string NameTovar { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public Nullable<int> Counts { get; set; }
        public Nullable<int> ID_type { get; set; }
        public Nullable<bool> Visiable { get; set; }
        public byte[] ImageTovar { get; set; }
    
        public virtual Type_Tovar Type_Tovar { get; set; }
    }
}
