//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamerShopStore.BDSHKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar_Sup
    {
        public int ID_tovarSup { get; set; }
        public string NameTovar { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CountsTovar { get; set; }
        public Nullable<int> CountsSup { get; set; }
        public Nullable<int> ID_type { get; set; }
        public Nullable<int> ID_sup { get; set; }
        public byte[] ImageTovar { get; set; }
        public Nullable<bool> VisibleSup { get; set; }
        public Nullable<bool> VisibleTovar { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Type_Tovar Type_Tovar { get; set; }
    }
}
